### ISSUE TITLE
Unable to load 'com.android.builder.Version' After Upgrade Gradle version from 4.1 to 4.4

### ISSUE THREAD

**Issue by Zhuhp** [mcxiaoke/packer-ng-plugin#120]
升级了gradle到4.4之后，就编译不过了。
提示：Caused by: java.lang.NoClassDefFoundError: com/android/builder/Version

**Comment by mcxiaoke** [comment]
暂时还没支持 Android Plugin 3.x，目前只能用Gradle 3.x版

**Comment by mcxiaoke** [comment]
最新版已支持
